version: '3.7'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "80:80"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --standalone -d creature-deck.mooo.com --non-interactive --agree-tos -m oscarquiroz@gmail.com --force-renewal
    networks:
      - webnet

networks:
  webnet: